### ISSUE TITLE
能否生成docker镜像

### ISSUE THREAD

**Issue by sln162** [stackia/rtp2httpd#2]
你好，我这边用的docker是精简版的，只能拉取镜像，我也不知道怎么生成镜像，能否帮忙生成一个镜像，包含arm64的版本，通过参数传入ip和port，占用您宝贵的时间，非常感谢

**Comment by sln162** [comment]
在chatGPT方式下实现了

**Comment by LIUBANGJIAN** [comment]
大佬，怎么生成的呢？

**Comment by stackia** [comment]
@LIUBANGJIAN 项目已经提供了构建好的 docker 镜像 https://github.com/stackia/rtp2httpd?tab=readme-ov-file#docker-容器部署
